### ISSUE TITLE
[VRG] 프로젝트 스캐폴딩

### ISSUE THREAD

**Issue by cadenzah** [cadenzah/video-resource-generator#9]
## Branch Name
`feature/9-vrg-project-scaffolding`

## Type of Change
`vrg`

## Priority
`high`

## Summary
VRG 서비스 구현을 위한 기본적인 프로젝트 스캐폴딩 작업

## Description of Change
- [x] Node.js 및 TypeScript 개발 환경 구축
- [x] Hello World 가능하도록 스캐폴딩 구축

## Reason for Change
본격적인 작업 시작을 위한 프로젝트 초기화 작업 - VRG

## Expected Next or Associated Work (If exists)
- [ ] 유저 시나리오 기반의 테스트 코드 작성 - #17
- [ ] 썸네일 스프라이트 생성 기능 - #10
- [ ] ~~미리보기 클립 생성 기능~~ → ~~현재 B tv 최신 UI에 관련 내용이 적용되었으므로, 폐기~~
- API 프로젝트 개발
  - [ ] 사용자에게 노출되는 URI 정의
- VID 프로젝트 개발
  - [ ] DB 연동 작업
  - [ ] 파일 업/다운로드 관련 모듈 (S3 사용)
  - [ ] 영상 ID 생성 모듈 - #11

## Estimated Story Point
10

## Reference (If exists)
- [TypeScript 기초 연습](https://velog.io/@velopert/typescript-basics)
- [Jest로 TypeScript 테스트 환경 만들기](https://gongzza.github.io/javascript/learning-typescript-with-jest/)
- [테스트 코드 작성하기 - jest, typescript](https://yonghyunlee.gitlab.io/temp_post/jest/)

**Comment by cadenzah** [comment]
'미리보기 클립 생성 기능'은 현재 B tv 최신 UI에 관련 기능이 반영되어 폐기할까 생각하였으나,
1. 내일 회사에서 매니저들께 '현재 회사 제품에 구현된 내용이라 하여 꼭 만들지 않아야 할 필요가 있는지' 여쭤보고 판단
2. 해당 기능을 활용하여 완결된 데모를 시연할 수 있다면 높은 평가를 받을 수 있지 않는지 등
을 고려하여 다시 생각해보기로 함.

**Comment by cadenzah** [comment]
## 🤔 '미리보기 클립'에 대한 피드백
- 최신 UI의 미리보기 기능은 영상 자체 내용이 아닌 예고편 등으로 구성된다
- 회차별 조회했을 때 미리보기를 수행하면 원본 영상을 모두 로드하여 전반 일부만을 재생하는 식으로 진행
  - *이 방식*과 비교하여 미리보기 클립이 더 효율적인지는 따져봐야 할 문제. 왜냐하면 *이 방식*은 CDN 통하여 캐싱된 자원을 받아오는 것이므로 빠를 수도 있기 때문
  - 🤔 근데... 미리보기 클립도 CDN에 저장한다면 동일 선상에서 비교할 수 있지 않나?

## 🤔 프로젝트 방향성에 대한 매니저님들 피드백
- 어차피 프로젝트를 구성하는 내용은 다양하므로, 100% FE라는 건 존재할 수 없음.
  - 오히려 멀티플레이어임을 어필하는 것은 좋을 수 있다
  - 게다가 내 프로젝트 내에는 데모 구현 등 FE 요소가 충분히 존재
- 주제나 방향성보다 결국 제일 중요한건 **최종 퀄리티와 완성도**. 결과물로 압도하자.
- 내가 자신감을 가지고서 기획하고 근거와 주장을 펴자
